### ISSUE TITLE
Cleanup of temporary upload files broken

### ISSUE THREAD

**Issue by frisi** [plone/plone.formwidget.namedfile#52] opened 2021-08-18 11:56 UTC
the current implementation removes dictionary items while iterating over the dictionary which leads to not all expired entries being deleted :

https://github.com/plone/plone.formwidget.namedfile/blob/3.0.0a3/plone/formwidget/namedfile/utils.py#L46-L53

```python
>>> mydict = {'one': 1, 'two': 2, 'three': 3, 'four': 4}
>>> for k,v in mydict.items():
...   if k == 'two':
...     del mydict[k]
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: dictionary changed size during iteration
```

**Comment by gforcada** [comment] 2022-11-30 04:25
Seems that the fix was not only applied to `master` branch but also to `2.x` 🎉 

I'm closing, as it seems the issue is solved, re-open if there is some work left still to do.

**Closed by gforcada** 2022-11-30 04:25 UTC
